stages:
  - deploy

pages:
  stage: deploy
  image: node
  only:
    - main
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
    - cp -r build/ public/
  artifacts:
    paths:
      - public/

