stages:
  - build

build:
  stage: build
  image: node
  only:
    - main
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!
    - mv build public
  artifacts:
    paths:
      - public/

